### ISSUE TITLE
Add {OHM}: {Olympus}

### ISSUE THREAD

**Issue by ohmapollo** [CamelotLabs/default-token-list#83]
- [X] I understand that token listing is not required to use the Camelot DEX Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Camelot DEX default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Blockchain(s): Mainnet, Arb
Token Address: 0xf0cb2dc0db5e6c66B9a70Ac27B06b878da017028
Token Name (from contract): Olympus
Token Decimals (from contract): 9
Token Symbol (from contract): OHM
Token Logo URI (square .svg or .png 256x256): https://arbiscan.io/token/images/olympusdao_32.png
Camelot V2 or V3 Pair Address of Token:V2

Link to the official homepage of token: https://www.olympusdao.finance/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/olympus

**Comment by 0xMyrddin** [comment]
Done
